#!/bin/bash

# 询问 jack happy 选择仓库名称
# 基于 AI 内容聚合器项目的名称建议

echo "╔═════════════════════════════════════╗"
echo "║  🐙 GitHub 仓库名称选择              ║"
echo "╚═════════════════════════════════════╝"
echo ""
echo "🎯 项目: AI 内容聚合器 (AI Content Aggregator)"
echo "📅 日期: $(date +%Y-%m-%d)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎨 我推荐的仓库名称（按优先级排序）"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  【推荐】 ai-content-hub"
echo "   简洁专业，易于记忆，SEO 友好"
echo "   适合作为主要产品名称"
echo ""
echo "2️⃣  【推荐】 clawdbot-hub"
echo "   体现协作背景，强化项目品牌"
echo "   清晰的"中心"概念"
echo ""
echo "3️⃣  ai-content-portal"
echo "   清晰的门户概念，专业且现代"
echo "   适合未来扩展"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎨 其他可选名称"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "4️⃣  content-fusion"
echo "   创意的"融合"概念，现代感强"
echo "   适合品牌化"
echo ""
echo "5️⃣  ai-content-aggregator"
echo "   技术准确，完整描述功能"
echo "   行业标准命名"
echo ""
echo "6️⃣  ai-content-merge"
echo "   "合并"含义明确，技术方向清晰"
echo "   简洁专业"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🌟 个人化选项（使用你的名字）"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "7️⃣  jack-ai-hub"
echo "   个人品牌化，清晰归属"
echo "   专业且友好"
echo ""
echo "8️⃣  jackhappy-content"
echo "   全名组合，完整表达"
echo "   适合个人项目"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 对比分析"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "名称               | 简洁性 | 专业性 | 易记性 | SEO | 扩展性"
echo "--------------------|--------|--------|--------|-----|--------"
echo "ai-content-hub     | ⭐⭐⭐⭐⭐ | ⭐⭐⭐⭐⭐ | ⭐⭐⭐⭐⭐ | ⭐⭐⭐⭐⭐ | ⭐⭐⭐⭐⭐"
echo "clawdbot-hub       | ⭐⭐⭐⭐⭐ | ⭐⭐⭐⭐⭐ | ⭐⭐⭐⭐⭐ | ⭐⭐⭐⭐ | ⭐⭐⭐⭐⭐"
echo "ai-content-portal  | ⭐⭐⭐⭐⭐ | ⭐⭐⭐⭐⭐ | ⭐⭐⭐⭐ | ⭐⭐⭐⭐⭐ | ⭐⭐⭐⭐⭐"
echo "content-fusion      | ⭐⭐⭐⭐ | ⭐⭐⭐⭐ | ⭐⭐⭐⭐⭐ | ⭐⭐⭐⭐ | ⭐⭐⭐⭐⭐"
echo "jack-ai-hub        | ⭐⭐⭐⭐⭐ | ⭐⭐⭐⭐ | ⭐⭐⭐⭐⭐ | ⭐⭐⭐⭐⭐ | ⭐⭐⭐⭐⭐"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 我的最终推荐"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "【首选】 ai-content-hub"
echo "   推荐理由：最平衡的选择，兼顾简洁、专业、SEO 和可扩展性"
echo ""
echo "【备选】 clawdbot-hub"
echo "   推荐理由：体现协作背景，强化项目品牌，适合未来多项目聚合"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 快速选择指南"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "• 追求最简洁专业 → 选择 ai-content-hub"
echo "• 强调协作和品牌 → 选择 clawdbot-hub"
echo "• 想要门户感 → 选择 ai-content-portal"
echo "• 喜欢创新概念 → 选择 content-fusion"
echo "• 想要技术准确 → 选择 ai-content-aggregator"
echo "• 个人化品牌 → 选择 jack-ai-hub 或 jackhappy-content"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 如何选择？"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "方式 1：快速选择"
echo "  输入 1-8 中的任意一个数字"
echo ""
echo "方式 2：自定义名称"
echo "  输入你喜欢的其他名称"
echo ""
echo "方式 3：使用我的推荐"
echo "  直接按 Enter 选择 ai-content-hub"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⏳ 等待你的选择..."
echo ""
