#!/bin/bash

# GitHub 自动上传脚本
# 将生成的文档推送到 GitHub

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="/root/clawd"
REPO_NAME="ultimate-skills-bundle"
BRANCH="main"
DOCS_PATH="ai-content-tracker/docs"

echo "🚀 准备上传文档到 GitHub..."
echo ""

# 检查仓库
REPO_PATH="$PROJECT_ROOT/$REPO_NAME"

if [ ! -d "$REPO_PATH" ]; then
    echo "❌ 仓库不存在: $REPO_PATH"
    echo ""
    echo "💡 使用 skills-bundle 仓库: /root/clawd/skills-bundle"
    REPO_PATH="/root/clawd/skills-bundle"
fi

if [ ! -d "$REPO_PATH" ]; then
    echo "❌ 仓库不存在: $REPO_PATH"
    exit 1
fi

cd "$REPO_PATH"

echo "📂 当前目录: $(pwd)"
echo "🔗 仓库: $REPO_NAME"
echo "🌿 分支: $BRANCH"
echo ""

# 检查是否有新的文档
DOCS_SOURCE="$SCRIPT_DIR/../docs"
DOCS_DEST="$REPO_PATH/$DOCS_PATH"

if [ ! -d "$DOCS_DEST" ]; then
    mkdir -p "$DOCS_DEST"
fi

# 复制新文档
if [ -d "$DOCS_SOURCE" ] && [ "$(ls -A $DOCS_SOURCE 2>/dev/null)" ]; then
    echo "📋 复制文档..."
    cp -r $DOCS_SOURCE/* $DOCS_DEST/
    echo "✅ 文档复制完成"
else
    echo "⚠️  没有新的文档"
    exit 0
fi

echo ""
echo "🔍 检查更改..."

# 检查是否有更改
if [ -z "$(git status --porcelain)" ]; then
    echo "✅ 没有新的更改"
    exit 0
fi

# 显示更改
git status --short

echo ""
echo "📝 提交更改..."

# 获取今天的日期
TODAY=$(date +%Y-%m-%d)

# 提交
git add $DOCS_PATH/
git commit -m "docs: 更新 AI 内容汇总 ($TODAY)

- 自动抓取 AI 玩法相关内容
- 更新热门内容统计
- 整理工具和媒体清单

Generated by: Clawdbot AI Content Tracker
Date: $TODAY"

echo "✅ 提交完成"
echo ""
echo "📤 推送到 GitHub..."

# 推送
git push origin $BRANCH

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ 推送成功！"
    echo ""
    echo "🔗 查看更新:"
    echo "   https://github.com/hhhh124hhhh/ultimate-skills-bundle/tree/main/$DOCS_PATH"
else
    echo "❌ 推送失败"
    exit 1
fi

echo ""
echo "🎉 完成！"
