#!/bin/bash
# AI Prompt Workflow - 使用示例
# 此脚本演示了如何使用整合的 AI 提示词工作流

set -e

echo "======================================"
echo "AI Prompt Workflow - 使用示例"
echo "======================================"
echo ""

# 示例1：基本使用
echo "示例1：基本使用（默认参数）"
echo "命令："
echo "  bash /root/clawd/scripts/integrated-prompt-workflow.sh"
echo ""
echo "说明："
echo "  - 查询: AI prompts"
echo "  - 每个源抓取: 50 个"
echo "  - 评估限制: 30 个"
echo "  - 质量阈值: 70"
echo ""
echo "--------------------------------------"
echo ""

# 示例2：自定义查询
echo "示例2：专注于创意写作"
echo "命令："
echo "  bash /root/clawd/scripts/integrated-prompt-workflow.sh \\"
echo "    --query \"creative writing\" \\"
echo "    --limit 100 \\"
echo "    --evaluate-limit 50 \\"
echo "    --quality-threshold 80"
echo ""
echo "说明："
echo "  - 查询: creative writing"
echo "  - 每个源抓取: 100 个（更多数据）"
echo "  - 评估限制: 50 个（更深度评估）"
echo "  - 质量阈值: 80（更严格的质量控制）"
echo ""
echo "--------------------------------------"
echo ""

# 示例3：测试模式
echo "示例3：测试模式（不发布）"
echo "命令："
echo "  bash /root/clawd/scripts/integrated-prompt-workflow.sh \\"
echo "    --test-mode"
echo ""
echo "说明："
echo "  - 执行完整的数据发现和评估流程"
echo "  - 生成 SKILL.md 文件"
echo "  - 不会发布到 ClawdHub"
echo "  - 适合审查和调试"
echo ""
echo "--------------------------------------"
echo ""

# 示例4：代码辅助
echo "示例4：编程技能自动化"
echo "命令："
echo "  bash /root/clawd/scripts/integrated-prompt-workflow.sh \\"
echo "    --query \"programming prompts code assistant\" \\"
echo "    --limit 80 \\"
echo "    --evaluate-limit 40 \\"
echo "    --quality-threshold 80"
echo ""
echo "说明："
echo "  - 专注于编程相关的提示词"
echo "  - 更严格的质量控制（80）"
echo "  - 适合构建代码辅助技能库"
echo ""
echo "--------------------------------------"
echo ""

# 示例5：AI 艺术
echo "示例5：AI 艺术提示词"
echo "命令："
echo "  bash /root/clawd/scripts/integrated-prompt-workflow.sh \\"
echo "    --query \"AI art prompts midjourney dalle\" \\"
echo "    --limit 100 \\"
echo "    --evaluate-limit 60 \\"
echo "    --quality-threshold 70"
echo ""
echo "说明："
echo "  - 收集图像生成提示词"
echo "  - 适用于 Midjourney、DALL-E、Stable Diffusion"
echo ""
echo "--------------------------------------"
echo ""

# 示例6：快速测试
echo "示例6：快速测试（最小参数）"
echo "命令："
echo "  bash /root/clawd/scripts/integrated-prompt-workflow.sh \\"
echo "    --limit 10 \\"
echo "    --evaluate-limit 5 \\"
echo "    --quality-threshold 60"
echo ""
echo "说明："
echo "  - 最小化数据收集和评估"
echo "  - 快速验证流程是否正常工作"
echo "  - 适合调试或测试"
echo ""
echo "--------------------------------------"
echo ""

# 定时任务示例
echo "定时任务示例："
echo ""
echo "# 每天早上 9 点运行"
echo "0 9 * * * cd /root/clawd && bash scripts/integrated-prompt-workflow.sh >> logs/cron-integrated.log 2>&1"
echo ""
echo "# 每天早上 9 点运行（高质量阈值）"
echo "0 9 * * * cd /root/clawd && bash scripts/integrated-prompt-workflow.sh --quality-threshold 85 >> logs/cron-integrated.log 2>&1"
echo ""
echo "# 每天早上 9 点运行（测试模式，不发布）"
echo "0 9 * * * cd /root/clawd && bash scripts/integrated-prompt-workflow.sh --test-mode >> logs/cron-integrated.log 2>&1"
echo ""
echo "# 每周一早上 8 点运行（更详细）"
echo "0 8 * * 1 cd /root/clawd && bash scripts/integrated-prompt-workflow.sh --limit 100 --evaluate-limit 50 >> logs/cron-integrated.log 2>&1"
echo ""
echo "--------------------------------------"
echo ""

# 查看结果
echo "查看结果："
echo ""
echo "# 查看最新报告"
echo "cat \$(ls -t /root/clawd/reports/integrated-workflow-report-*.md | head -1)"
echo ""
echo "# 查看日志"
echo "tail -f /root/clawd/logs/integrated-prompt-workflow.log"
echo ""
echo "# 查看生成的 skills"
echo "ls -la /root/clawd/skills/ | tail -20"
echo ""
echo "--------------------------------------"
echo ""

echo "✅ 示例演示完成！"
echo ""
echo "提示："
echo "1. 首次使用建议先运行 --test-mode 验证流程"
echo "2. 查看日志确保没有错误"
echo "3. 调整质量阈值以获得合适的结果数量"
echo "4. 使用 cron 设置定期自动运行"
echo ""
echo "详细文档："
echo "  - SKILL.md: 完整文档"
echo "  - README.md: 快速入门"
