#!/bin/bash

# Test script for improved Twitter search
# This script demonstrates how to use the improved search features

echo "=============================================="
echo "Twitter Search Improved Script - Test Guide"
echo "=============================================="
echo ""

echo "Step 1: Configure API Key"
echo "--------------------------"
echo "Before running the search, set your Twitter API key:"
echo ""
echo "  export TWITTER_API_KEY='your_api_key_here'"
echo ""
echo "Or add permanently:"
echo "  echo \"export TWITTER_API_KEY='your_api_key_here'\" >> ~/.bashrc"
echo "  source ~/.bashrc"
echo ""

echo "Step 2: Quick Test"
echo "------------------"
echo "Test the improved script with a small query:"
echo ""
echo "  cd /root/clawd/skills/twitter-search-skill/scripts"
echo "  ./run_search_improved.sh --smart-query clawdbot --max-results 20"
echo ""

echo "Step 3: High-Quality AI Prompts Search"
echo "---------------------------------------"
echo "Search for AI prompts with quality filters:"
echo ""
echo "  ./run_search_improved.sh --smart-query prompts \\"
echo "    --lang en \\"
echo "    --min-likes 10 \\"
echo "    --min-retweets 5 \\"
echo "    --max-results 50"
echo ""

echo "Step 4: Automation Trends Search"
echo "--------------------------------"
echo "Discover AI automation trends:"
echo ""
echo "  ./run_search_improved.sh --smart-query automation \\"
echo "    --lang en \\"
echo "    --min-likes 20 \\"
echo "    --min-retweets 10 \\"
echo "    --max-results 100"
echo ""

echo "Step 5: Custom Query"
echo "--------------------"
echo "Use a custom query with filters:"
echo ""
echo "  ./run_search_improved.sh \"\\\"prompt engineering\\\" OR \\\"ChatGPT prompts\\\"\" \\"
echo "    --lang en \\"
echo "    --min-likes 30 \\"
echo "    --min-retweets 15 \\"
echo "    --max-results 100"
echo ""

echo "=============================================="
echo "Output Format Options"
echo "=============================================="
echo ""
echo "Full JSON with all tweets:"
echo "  ./run_search_improved.sh --smart-query prompts --format json"
echo ""
echo "Summary only (default):"
echo "  ./run_search_improved.sh --smart-query prompts --format summary"
echo ""

echo "=============================================="
echo "Query Type Options"
echo "=============================================="
echo ""
echo "Top (relevance-ranked, default):"
echo "  ./run_search_improved.sh --smart-query prompts --query-type Top"
echo ""
echo "Latest (chronological):"
echo "  ./run_search_improved.sh --smart-query prompts --query-type Latest"
echo ""

echo "=============================================="
echo "Smart Query Templates"
echo "=============================================="
echo ""
echo "Available templates:"
echo "  - prompts: AI prompts, prompt engineering, ChatGPT/Claude prompts"
echo "  - automation: AI automation, workflows, agents, tools"
echo "  - tools: AI tools, software, applications, startups"
echo "  - clawdbot: Clawdbot-specific searches"
echo ""

echo "=============================================="
echo "Filter Thresholds"
echo "=============================================="
echo ""
echo "Recommended thresholds for different use cases:"
echo ""
echo "High-quality content (Skill ideas):"
echo "  --min-likes 50 --min-retweets 20 --min-replies 10"
echo ""
echo "Moderate quality (Trend analysis):"
echo "  --min-likes 20 --min-retweets 10 --min-replies 5"
echo ""
echo "Low threshold (Brand monitoring):"
echo "  --min-likes 5 --min-retweets 2 --min-replies 1"
echo ""
echo "No threshold (Exploratory):"
echo "  --min-likes 0 --min-retweets 0 --min-replies 0"
echo ""

echo "=============================================="
echo "Files Created"
echo "=============================================="
echo ""
echo "  1. twitter_search_improved.py - Enhanced search script"
echo "  2. run_search_improved.sh - Wrapper with auto-loading"
echo "  3. IMPROVEMENTS.md - Detailed documentation"
echo "  4. README_IMPROVEMENTS.md - Quick start guide"
echo "  5. SKILL.md (updated) - Added improved script section"
echo "  6. test_improved.sh - This test guide"
echo ""

echo "=============================================="
echo "Documentation"
echo "=============================================="
echo ""
echo "Quick Start:     README_IMPROVEMENTS.md"
echo "Full Details:    IMPROVEMENTS.md"
echo "Skill Docs:      ../SKILL.md"
echo ""

echo "=============================================="
echo "Ready to Test?"
echo "=============================================="
echo ""
echo "Set your API key and run:"
echo ""
echo "  export TWITTER_API_KEY='your_api_key'"
echo "  cd /root/clawd/skills/twitter-search-skill/scripts"
echo "  ./run_search_improved.sh --smart-query clawdbot --max-results 20"
echo ""
echo "=============================================="
