#!/usr/bin/env python3
"""
从已收集的数据中提取 Prompts 并转换为 Skills
"""

import json
import os
import hashlib
from datetime import datetime

# 数据源
DATA_SOURCES = [
    '/root/clawd/data/prompts/github-awesome-prompts.jsonl',
    '/root/clawd/data/prompts/reddit-prompts.jsonl',
    '/root/clawd/data/prompts/hacker-news-ai.jsonl',
    '/root/clawd/data/prompts/collected.jsonl'
]

# 输出目录
OUTPUT_DIR = "/root/clawd/generated-skills"
PROMPT_TYPES = ['生图', '生视频', 'AI 编码', '提示词工程']

def extract_prompt_from_data(data):
    """从数据中提取 prompt"""
    content = ''
    
    # 尝试从不同字段提取
    if 'content' in data:
        content = str(data['content'])
    elif 'text' in data:
        content = str(data['text'])
    elif 'prompt' in data:
        content = str(data['prompt'])
    elif 'description' in data:
        content = str(data['description'])
    
    # 清理内容
    content = content.strip()
    
    # 限制长度
    if len(content) > 2000:
        content = content[:2000] + "..."
    
    return content

def categorize_prompt(data):
    """分类 prompt 类型"""
    content = extract_prompt_from_data(data).lower()
    title = data.get('title', '').lower()
    tags = data.get('tags', [])
    
    if not content and not title:
        return '通用'
    
    # 检查生图相关关键词
    image_keywords = ['生图', '绘图', '画图', '图片', 'image', 'midjourney', 'dalle', 
                    'stable diffusion', 'diffusion', 'leonardo', 'firefly', 
                    'starryai', 'playgroundai', 'runwayml']
    
    # 检查生视频相关关键词
    video_keywords = ['生视频', '视频生成', 'video', 'kling', 'runway', 
                    'pika', 'sora', '做视频', '视频编辑']
    
    # 检查 AI 编码相关关键词
    coding_keywords = ['编码', '编程', 'coding', 'code', '代码', '开发', 'development',
                    '程序员', 'developer', 'ide', 'editor']
    
    # 检查提示词工程相关关键词
    prompt_keywords = ['prompt', '提示词', 'template', '模板', '指令', 'instruction']
    
    text = content + ' ' + title + ' ' + ' '.join(str(t) for t in tags).lower()
    
    for keyword in image_keywords:
        if keyword in text:
            return '生图'
    
    for keyword in video_keywords:
        if keyword in text:
            return '生视频'
    
    for keyword in coding_keywords:
        if keyword in text:
            return 'AI 编码'
    
    for keyword in prompt_keywords:
        if keyword in text:
            return '提示词工程'
    
    return '通用'

def calculate_quality_score(data):
    """计算质量分数（0-100）"""
    score = 0
    
    content = extract_prompt_from_data(data)
    title = data.get('title', '')
    likes = data.get('likes', 0) or data.get('upvotes', 0) or data.get('stars', 0)
    comments = data.get('comments', 0) or data.get('num_comments', 0) or data.get('replies', 0)
    
    # 内容长度评分
    if len(content) > 200:
        score += 10
    if len(content) > 500:
        score += 10
    if len(content) > 1000:
        score += 10
    
    # 互动评分
    if likes > 0:
        import math
        score += min(20, math.log2(likes + 1) * 3)
    
    if comments > 0:
        import math
        score += min(10, math.log2(comments + 1) * 2)
    
    # 标题长度评分
    if len(title) > 20:
        score += 10
    if len(title) > 50:
        score += 10
    
    # 包含示例或模板
    text = content + ' ' + title
    if 'example' in text.lower() or 'template' in text.lower() or '示例' in text:
        score += 20
    
    return min(100, score)

def create_skill_from_prompt(data, prompt_type):
    """从 prompt 创建 skill"""
    content = extract_prompt_from_data(data)
    
    if not content or len(content) < 20:
        return None
    
    # 生成唯一 ID
    content_hash = hashlib.md5(content.encode()).hexdigest()[:8]
    source_name = data.get('source', 'unknown').lower()
    skill_name = f"{prompt_type.lower()}-{source_name}-{content_hash}"
    
    # 创建 skill 目录
    skill_dir = os.path.join(OUTPUT_DIR, skill_name)
    os.makedirs(skill_dir, exist_ok=True)
    
    # 生成 SKILL.md
    skill_md = f"""# {prompt_type} Prompt Skill

## 描述
{content[:100]}...

## 类型
- 类型: {prompt_type}
- 评分: {calculate_quality_score(data):.0f}/100

## Prompt
```
{content[:1000] if len(content) > 1000 else content}
```

## 来源信息
- 来源: {data.get('source', 'N/A')}
- 原始链接: {data.get('url', 'N/A')}
- 作者: {data.get('author', 'N/A')}
- 互动: {data.get('likes', 0)} 赞

## 元数据
- 收集时间: {datetime.now().isoformat()}
- Prompt 类型: {prompt_type}
- 质量分数: {calculate_quality_score(data):.0f}/100

---

*Skill generated by Clawdbot*
"""
    
    # 保存 SKILL.md
    with open(os.path.join(skill_dir, 'SKILL.md'), 'w', encoding='utf-8') as f:
        f.write(skill_md)
    
    # 创建 metadata.json
    metadata = {
        "name": f"{prompt_type} Prompt from {data.get('source', 'N/A')}",
        "version": "1.0.0",
        "description": content[:100] if len(content) > 100 else content,
        "author": "Clawdbot",
        "type": prompt_type,
        "source": data.get('source', 'N/A'),
        "url": data.get('url', ''),
        "created_at": datetime.now().isoformat()
    }
    
    with open(os.path.join(skill_dir, 'metadata.json'), 'w', encoding='utf-8') as f:
        json.dump(metadata, f, indent=2, ensure_ascii=False)
    
    return {
        'name': skill_name,
        'path': skill_dir,
        'type': prompt_type,
        'score': calculate_quality_score(data)
    }

def main():
    print("=" * 80)
    print("🔄 从已收集的数据中提取 Prompts 并转换为 Skills")
    print("=" * 80)
    print()
    
    # 创建输出目录
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    # 读取所有数据
    all_data = []
    for source_file in DATA_SOURCES:
        if os.path.exists(source_file):
            print(f"📖 读取: {source_file}")
            try:
                with open(source_file, 'r', encoding='utf-8') as f:
                    for line in f:
                        if not line.strip():
                            continue
                        try:
                            data = json.loads(line)
                            all_data.append(data)
                        except:
                            continue
                print(f"  ✓ 读取了 {len(all_data)} 条数据")
            except Exception as e:
                print(f"  ⚠️  读取失败: {e}")
    
    print()
    print(f"📊 总共读取 {len(all_data)} 条数据")
    print()
    
    # 分类和提取 Prompts
    categorized_prompts = {
        '生图': [],
        '生视频': [],
        'AI 编码': [],
        '提示词工程': [],
        '通用': []
    }
    
    for data in all_data:
        prompt_type = categorize_prompt(data)
        categorized_prompts[prompt_type].append({
            'data': data,
            'type': prompt_type
        })
    
    print("📂 数据分类:")
    for prompt_type, prompts in categorized_prompts.items():
        print(f"  {prompt_type}: {len(prompts)} 条")
    print()
    
    # 创建 Skills
    print("🔄 转换为 Skills...")
    all_skills = []
    stats = {
        '生图': 0,
        '生视频': 0,
        'AI 编码': 0,
        '提示词工程': 0,
        '通用': 0,
        'total': 0,
        'skipped': 0
    }
    
    for prompt_type, prompts in categorized_prompts.items():
        print(f"  处理 {prompt_type} Prompts ({len(prompts)} 条)...")
        
        for item in prompts:
            data = item['data']
            quality_score = calculate_quality_score(data)
            
            # 只保留高质量 Prompts（>= 60 分）
            if quality_score >= 60:
                skill = create_skill_from_prompt(data, prompt_type)
                if skill:
                    all_skills.append(skill)
                    stats[prompt_type] += 1
                    stats['total'] += 1
            else:
                stats['skipped'] += 1
    
        print(f"  ✓ 转换了 {stats[prompt_type]} 个 Skills")
    
    print()
    print(f"📊 转换统计:")
    print(f"  总数据: {len(all_data)} 条")
    print(f"  已转换: {stats['total']} 个 Skills")
    print(f"  跳过（低质量）: {stats['skipped']} 条")
    print()
    
    for prompt_type, count in stats.items():
        if prompt_type not in ['total', 'skipped']:
            print(f"  {prompt_type}: {count} 个")
    
    print()
    print(f"✅ 已生成 {stats['total']} 个 Skills")
    print(f"📁 保存位置: {OUTPUT_DIR}")
    print()
    
    # 生成报告
    timestamp = datetime.now().strftime('%Y-%m-%d')
    report = {
        "timestamp": datetime.now().isoformat(),
        "total_data": len(all_data),
        "converted_skills": stats['total'],
        "skipped": stats['skipped'],
        "by_type": stats
    }
    
    report_file = os.path.join(OUTPUT_DIR, f"prompt-to-skill-conversion-{timestamp}.json")
    with open(report_file, 'w', encoding='utf-8') as f:
        json.dump(report, f, indent=2, ensure_ascii=False)
    
    print(f"📄 报告已保存: {report_file}")
    print()
    print("=" * 80)
    print("✅ Prompts 转 Skills 完成！")
    print("=" * 80)
    print()
    
    # 显示 Top 10 Skills
    print("🏆 Top 10 Skills (按质量分数排序）:")
    print()
    
    sorted_skills = sorted(all_skills, key=lambda x: x['score'], reverse=True)
    for i, skill in enumerate(sorted_skills[:10], 1):
        print(f"{i}. [{skill['score']}] {skill['name']} ({skill['type']})")
    
    return all_skills

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⏸️  用户中断")
    except Exception as e:
        print(f"\n\n❌ 错误: {e}")
        import traceback
        traceback.print_exc()
