#!/usr/bin/env python3
"""
将 V2 Prompts 转换成 Skills
使用 completeness_score ≥ 70 的高质量提示词
"""

import json
import os
import re
import hashlib
from datetime import datetime
from collections import defaultdict

# 配置
PROMPTS_DIR = "/root/clawd/data/prompts"
SKILLS_OUTPUT_DIR = "/root/clawd/dist/skills"

# 高质量阈值 - 使用 completeness_score
MIN_COMPLETENESS_SCORE = 70

def deduplicate_prompts(prompts):
    """
    提示词去重算法
    基于内容相似度去重
    """
    # 第一层：完全相同的提示词
    seen_hashes = set()
    deduped = []

    for prompt in prompts:
        content = prompt.get('content', '').strip().lower()
        content_hash = hashlib.md5(content.encode()).hexdigest()

        if content_hash not in seen_hashes:
            seen_hashes.add(content_hash)
            deduped.append(prompt)

    # 第二层：相似度去重（简单的词袋模型）
    # 去除停用词和常见词
    stop_words = {'the', 'a', 'an', 'is', 'are', 'was', 'were', 'be', 'been',
                  'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would',
                  'can', 'could', 'should', 'may', 'might', 'must', 'with',
                  'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for', 'of',
                  'by', 'from', 'as', 'that', 'this', 'these', 'those'}

    # 计算单词集合相似度
    def get_word_set(text):
        words = re.findall(r'\b\w+\b', text.lower())
        return set(word for word in words if word not in stop_words and len(word) > 2)

    final_deduped = []
    seen_word_sets = []

    for prompt in deduped:
        content = prompt.get('content', '')
        word_set = get_word_set(content)

        # 检查与已存在的相似度
        is_duplicate = False
        for existing_set in seen_word_sets:
            # Jaccard 相似度
            intersection = len(word_set & existing_set)
            union = len(word_set | existing_set)

            if union > 0 and intersection / union > 0.85:  # 85% 相似度阈值
                is_duplicate = True
                break

        if not is_duplicate:
            final_deduped.append(prompt)
            seen_word_sets.append(word_set)

    return final_deduped

def create_skill_from_prompt(prompt_data, skill_type_suffix):
    """从 prompt 创建 skill"""
    content = prompt_data.get('content', '')
    title = prompt_data.get('title', 'AI ' + skill_type_suffix)
    source = prompt_data.get('source', '')
    url = prompt_data.get('url', '')
    prompt_type = prompt_data.get('prompt_type', 'general')
    completeness_score = prompt_data.get('completeness_score', 0)

    if not content:
        return None

    # 生成完整的 description
    description = content[:500] + "..." if len(content) > 500 else content
    prompt_display = content[:1000] + "..." if len(content) > 1000 else content

    # 生成唯一的 skill name
    content_hash = hashlib.md5(content.encode()).hexdigest()[:8]
    skill_name_clean = title.lower()
    skill_name_clean = re.sub(r'[^a-z0-9\s-]', '-', skill_name_clean)
    skill_name_clean = re.sub(r'\s+', '-', skill_name_clean)
    skill_name_clean = re.sub(r'-+', '-', skill_name_clean)
    skill_name_clean = skill_name_clean.strip('-')
    skill_name_clean = skill_name_clean[:50]
    skill_name_final = f"{skill_name_clean}-{content_hash}"

    # 生成 SKILL.md with proper YAML frontmatter
    skill_md = f"""---
name: {skill_name_final}
description: {description}
metadata: {{"clawdbot":{{"type":"{prompt_type}","source":"{source}","original_url":"{url}","completeness_score":{completeness_score}}}}}
---

# {title}

## 描述
{description}

## 来源
- 平台: {source}
- 原始链接: {url}
- 类型: {prompt_type}
- 完整性分数: {completeness_score}/100

## Prompt
```
{prompt_display}
```

---

## 标签
- AI
- {prompt_type}
- prompt
- 高质量
- 完整性-{completeness_score}

---

*Skill generated by Clawdbot from V2 prompts*
"""

    # 创建 skill 目录
    skill_dir = os.path.join(SKILLS_OUTPUT_DIR, skill_name_final)
    os.makedirs(skill_dir, exist_ok=True)

    # 保存 SKILL.md
    with open(os.path.join(skill_dir, "SKILL.md"), 'w', encoding='utf-8') as f:
        f.write(skill_md)

    # 创建 metadata.json
    metadata = {
        "name": title,
        "version": "1.0.0",
        "description": description,
        "author": "Clawdbot",
        "type": prompt_type,
        "source": source,
        "url": url,
        "completeness_score": completeness_score,
        "created_at": datetime.now().isoformat()
    }

    with open(os.path.join(skill_dir, "metadata.json"), 'w', encoding='utf-8') as f:
        f.write(json.dumps(metadata, indent=2, ensure_ascii=False))

    return {
        "name": skill_name_final,
        "path": skill_dir,
        "md_file": os.path.join(skill_dir, "SKILL.md"),
        "metadata": metadata,
        "prompt_type": prompt_type
    }

def main():
    print("=" * 80)
    print("🔄 转换 V2 Prompts 为 Skills (使用 completeness_score ≥ 70)")
    print("=" * 80)
    print()

    # 检查输入文件
    image_prompts_file = os.path.join(PROMPTS_DIR, "image-prompts-v2.jsonl")
    video_prompts_file = os.path.join(PROMPTS_DIR, "video-prompts-v2.jsonl")
    general_prompts_file = os.path.join(PROMPTS_DIR, "general-prompts-v2.jsonl")

    all_prompts = []
    all_skills = []
    stats = {
        "image_prompts": 0,
        "video_prompts": 0,
        "general_prompts": 0,
        "high_quality": 0,
        "converted_image": 0,
        "converted_video": 0,
        "converted_general": 0,
        "skipped_low_quality": 0
    }

    # 1. 读取图像提示词
    if os.path.exists(image_prompts_file):
        print("[1/3] 读取图像 Prompts...")
        with open(image_prompts_file, 'r', encoding='utf-8') as f:
            for line in f:
                if not line.strip():
                    continue
                try:
                    prompt_data = json.loads(line)
                    all_prompts.append(prompt_data)
                    stats["image_prompts"] += 1
                except Exception as e:
                    pass
        print(f"  ✓ 读取完成: {stats['image_prompts']} 条")
        print()

    # 2. 读取视频提示词
    if os.path.exists(video_prompts_file):
        print("[2/3] 读取视频 Prompts...")
        with open(video_prompts_file, 'r', encoding='utf-8') as f:
            for line in f:
                if not line.strip():
                    continue
                try:
                    prompt_data = json.loads(line)
                    all_prompts.append(prompt_data)
                    stats["video_prompts"] += 1
                except Exception as e:
                    pass
        print(f"  ✓ 读取完成: {stats['video_prompts']} 条")
        print()

    # 3. 读取通用提示词
    if os.path.exists(general_prompts_file):
        print("[3/3] 读取通用 Prompts...")
        with open(general_prompts_file, 'r', encoding='utf-8') as f:
            for line in f:
                if not line.strip():
                    continue
                try:
                    prompt_data = json.loads(line)
                    all_prompts.append(prompt_data)
                    stats["general_prompts"] += 1
                except Exception as e:
                    pass
        print(f"  ✓ 读取完成: {stats['general_prompts']} 条")
        print()

    print("=" * 80)
    print("📊 数据质量分析")
    print("=" * 80)

    # 4. 去重
    print(f"\n[4/5] 去重处理...")
    original_count = len(all_prompts)
    all_prompts = deduplicate_prompts(all_prompts)
    deduped_count = len(all_prompts)
    duplicates_removed = original_count - deduped_count
    print(f"  ✓ 原始提示词: {original_count}")
    print(f"  ✓ 去重后: {deduped_count}")
    print(f"  ✓ 移除重复: {duplicates_removed}")
    print()

    # 5. 筛选高质量提示词
    print(f"[5/5] 筛选高质量提示词 (completeness_score ≥ {MIN_COMPLETENESS_SCORE})...")
    high_quality_prompts = [p for p in all_prompts if p.get('completeness_score', 0) >= MIN_COMPLETENESS_SCORE]
    low_quality_prompts = [p for p in all_prompts if p.get('completeness_score', 0) < MIN_COMPLETENESS_SCORE]

    stats["high_quality"] = len(high_quality_prompts)
    stats["skipped_low_quality"] = len(low_quality_prompts)

    print(f"  ✓ 高质量 (≥{MIN_COMPLETENESS_SCORE}): {stats['high_quality']} 条")
    print(f"  ✓ 低质量 (<{MIN_COMPLETENESS_SCORE}): {stats['skipped_low_quality']} 条")
    print()

    # 6. 按类型分类生成技能
    print("=" * 80)
    print("🎨 按类型生成 Skills")
    print("=" * 80)
    print()

    type_stats = defaultdict(int)
    for prompt_data in high_quality_prompts:
        prompt_type = prompt_data.get('prompt_type', 'general')
        completeness_score = prompt_data.get('completeness_score', 0)

        # 确定技能类型后缀
        if prompt_type == 'image-generation':
            suffix = "Image Generation"
        elif prompt_type == 'video-generation':
            suffix = "Video Generation"
        elif prompt_type == 'text-generation':
            suffix = "Text Generation"
        else:
            suffix = "General"

        # 创建 skill
        skill = create_skill_from_prompt(prompt_data, suffix)
        if skill:
            all_skills.append(skill)
            type_stats[prompt_type] += 1

            if prompt_type == 'image-generation':
                stats["converted_image"] += 1
            elif prompt_type == 'video-generation':
                stats["converted_video"] += 1
            elif prompt_type == 'text-generation':
                stats["converted_general"] += 1
            else:
                stats["converted_general"] += 1

    print(f"✅ Skills 生成完成:")
    for ptype, count in sorted(type_stats.items()):
        print(f"  - {ptype}: {count} 个")
    print()

    # 7. 打包成 .skill 文件
    print("=" * 80)
    print("📦 打包成 .skill 文件")
    print("=" * 80)
    print()

    os.makedirs(SKILLS_OUTPUT_DIR, exist_ok=True)

    packaged_count = 0
    for skill in all_skills:
        skill_name = skill["name"]
        skill_path = skill["path"]

        import zipfile
        skill_file = os.path.join(SKILLS_OUTPUT_DIR, f"{skill_name}.skill")

        try:
            with zipfile.ZipFile(skill_file, 'w', zipfile.ZIP_DEFLATED) as zipf:
                for root, dirs, files in os.walk(skill_path):
                    for file in files:
                        file_path = os.path.join(root, file)
                        arcname = os.path.relpath(file_path, skill_path)
                        zipf.write(file_path, arcname)

            packaged_count += 1
            print(f"  ✓ {skill_name}.skill ({skill['prompt_type']}, score: {skill['metadata'].get('completeness_score', 0)})")
        except Exception as e:
            print(f"  ⚠️  打包失败 {skill_name}: {e}")

    print()
    print(f"✅ 打包完成: {packaged_count} 个 .skill 文件")
    print()

    # 8. 生成详细报告
    print("=" * 80)
    print("📄 生成详细报告")
    print("=" * 80)
    print()

    timestamp = datetime.now().strftime('%Y-%m-%d')
    report_file = os.path.join(PROMPTS_DIR, f"v2-skill-generation-{timestamp}.json")

    report = {
        "timestamp": datetime.now().isoformat(),
        "config": {
            "min_completeness_score": MIN_COMPLETENESS_SCORE,
            "deduplication": "enabled",
            "similarity_threshold": 0.85
        },
        "stats": stats,
        "deduplication": {
            "original_count": original_count,
            "deduped_count": deduped_count,
            "duplicates_removed": duplicates_removed
        },
        "quality_filtering": {
            "high_quality": len(high_quality_prompts),
            "low_quality": len(low_quality_prompts),
            "pass_rate": f"{len(high_quality_prompts)/deduped_count*100:.1f}%" if deduped_count > 0 else "0%"
        },
        "type_distribution": dict(type_stats),
        "total_prompts": stats['image_prompts'] + stats['video_prompts'] + stats['general_prompts'],
        "total_converted": stats['converted_image'] + stats['converted_video'] + stats['converted_general'],
        "total_packaged": packaged_count,
        "output_dir": SKILLS_OUTPUT_DIR
    }

    with open(report_file, 'w', encoding='utf-8') as f:
        f.write(json.dumps(report, indent=2, ensure_ascii=False))

    print(f"✅ 报告已保存: {report_file}")
    print()

    # 9. 生成 Markdown 可读报告
    markdown_report_file = os.path.join(PROMPTS_DIR, f"v2-skill-generation-{timestamp}.md")

    markdown_report = f"""# V2 Prompts 转 Skills 生成报告

**时间**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## 📊 处理统计

### 输入数据
| 文件 | 数量 |
|------|------|
| 图像 Prompts | {stats['image_prompts']} |
| 视频 Prompts | {stats['video_prompts']} |
| 通用 Prompts | {stats['general_prompts']} |
| **总计** | **{stats['image_prompts'] + stats['video_prompts'] + stats['general_prompts']}** |

### 数据处理
| 阶段 | 数量 |
|------|------|
| 原始提示词 | {original_count} |
| 去重后 | {deduped_count} |
| 移除重复 | {duplicates_removed} |
| 高质量 (≥{MIN_COMPLETENESS_SCORE}) | {len(high_quality_prompts)} |
| 低质量 (<{MIN_COMPLETENESS_SCORE}) | {len(low_quality_prompts)} |
| **通过率** | **{len(high_quality_prompts)/deduped_count*100:.1f}%** |

### Skill 生成
| 类型 | 数量 |
|------|------|
"""
    for ptype, count in sorted(type_stats.items()):
        markdown_report += f"| {ptype} | {count} |\n"

    markdown_report += f"""| **总计** | **{stats['converted_image'] + stats['converted_video'] + stats['converted_general']}** |
| 打包文件 | {packaged_count} .skill |

## 🎯 配置参数

- **最低完整性分数**: {MIN_COMPLETENESS_SCORE}
- **去重算法**: 已启用
- **相似度阈值**: 85% (Jaccard 相似度)
- **停用词过滤**: 已启用

## 📈 完整性分数分布

"""

    # 计算分数分布
    if high_quality_prompts:
        scores = [p.get('completeness_score', 0) for p in high_quality_prompts]
        excellent = sum(1 for s in scores if s >= 90)
        good = sum(1 for s in scores if 80 <= s < 90)
        medium = sum(1 for s in scores if 70 <= s < 80)

        markdown_report += f"""
| 分数区间 | 数量 | 占比 |
|----------|------|------|
| 优秀 (≥90) | {excellent} | {excellent/len(scores)*100:.1f}% |
| 良好 (80-89) | {good} | {good/len(scores)*100:.1f}% |
| 及格 (70-79) | {medium} | {medium/len(scores)*100:.1f}% |
| **总计** | **{len(scores)}** | 100% |
"""

    markdown_report += f"""
## 🔧 去重算法

### 第一层：完全重复
- 使用 MD5 哈希检测完全相同的提示词
- 移除所有完全重复的条目

### 第二层：相似度去重
- 使用 Jaccard 相似度（词袋模型）
- 去除停用词（如 "the", "and", "is" 等）
- 相似度阈值：85%
- 保留质量更高（completeness_score）的版本

## 📁 输出文件

- **Skills 目录**: {SKILLS_OUTPUT_DIR}
- **JSON 报告**: {report_file}
- **Markdown 报告**: {markdown_report_file}

## 📝 质量标准

### 提示词完整性评分（0-100）
1. **长度适当** (25分) - 50-300字符最优
2. **包含主语** (15分) - 描述对象
3. **描述风格** (15分) - 风格关键词
4. **描述环境** (15分) - 环境描述
5. **光照描述** (10分) - 光照关键词
6. **情绪氛围** (10分) - 情绪描述
7. **技术参数** (10分) - 参数标记

## ✅ 生成完成

所有高质量提示词已成功转换为 Skills，并按类型分类打包。

---

*报告自动生成 | V2 Skill Conversion*
"""

    with open(markdown_report_file, 'w', encoding='utf-8') as f:
        f.write(markdown_report)

    print(f"✅ Markdown 报告已保存: {markdown_report_file}")
    print()

    # 最终总结
    print("=" * 80)
    print("✅ 转换完成！")
    print("=" * 80)
    print()
    print(f"📊 最终统计:")
    print(f"  输入 Prompts:")
    print(f"    图像: {stats['image_prompts']} 条")
    print(f"    视频: {stats['video_prompts']} 条")
    print(f"    通用: {stats['general_prompts']} 条")
    print(f"    总计: {stats['image_prompts'] + stats['video_prompts'] + stats['general_prompts']} 条")
    print()
    print(f"  去重处理:")
    print(f"    原始: {original_count} 条")
    print(f"    去重后: {deduped_count} 条")
    print(f"    移除: {duplicates_removed} 条重复")
    print()
    print(f"  质量筛选 (≥{MIN_COMPLETENESS_SCORE}):")
    print(f"    高质量: {len(high_quality_prompts)} 条")
    print(f"    低质量: {len(low_quality_prompts)} 条")
    print()
    print(f"  Skill 生成:")
    print(f"    图像生成: {stats['converted_image']} 个")
    print(f"    视频生成: {stats['converted_video']} 个")
    print(f"    文本/通用: {stats['converted_general']} 个")
    print(f"    总计: {stats['converted_image'] + stats['converted_video'] + stats['converted_general']} 个")
    print()
    print(f"  打包: {packaged_count} 个 .skill 文件")
    print()
    print(f"📁 输出目录: {SKILLS_OUTPUT_DIR}")
    print(f"📄 报告: {markdown_report_file}")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⏸️  用户中断")
    except Exception as e:
        print(f"\n\n❌ 错误: {e}")
        import traceback
        traceback.print_exc()
